apiVersion: apps/v1
kind: Deployment

metadata:
  name: mini-webserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mini-webserver
  template:
    metadata:
      labels:
        app: mini-webserver
    spec:
      containers:
        - name: webserver
          image: mini-webserver:latest
          ports:
            - containerPort: 8080
